"""Add work queue and enhance audiobook models

Revision ID: 3c7acc64b5ab
Revises:
Create Date: 2024-11-25 20:56:36.447487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic.operations import ops


# revision identifiers, used by Alembic.
revision: str = '3c7acc64b5ab'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('work_queue',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('content_piece_id', sa.Integer(), nullable=False),
        sa.Column('audiobook_id', sa.Integer(), nullable=False),
        sa.Column('priority', sa.Integer(), nullable=True),
        sa.Column('status', sa.Enum('pending', 'in_progress', 'completed', 'failed', name='queue_status'), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('started_at', sa.DateTime(), nullable=True),
        sa.Column('completed_at', sa.DateTime(), nullable=True),
        sa.Column('worker_id', sa.String(), nullable=True),
        sa.Column('error_message', sa.String(), nullable=True),
        sa.ForeignKeyConstraint(['audiobook_id'], ['audiobooks.id'], ),
        sa.ForeignKeyConstraint(['content_piece_id'], ['content_pieces.id'], ),
        sa.PrimaryKeyConstraint('id')
    )

    op.add_column('audiobooks', sa.Column('description', sa.String(), nullable=True))
    op.add_column('audiobooks', sa.Column('forked_from_id', sa.Integer(), nullable=True))
    op.add_column('audiobooks', sa.Column('created_at', sa.DateTime(), nullable=True))

    # Replace the direct foreign key creation with batch operations
    with op.batch_alter_table('audiobooks') as batch_op:
        batch_op.create_foreign_key('audiobooks_forked_from_id_fkey', 'audiobooks', ['forked_from_id'], ['id'])

    op.add_column('voice_performances', sa.Column('worker_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('voice_performances', 'worker_id')
    op.drop_constraint(None, 'audiobooks', type_='foreignkey')
    op.drop_column('audiobooks', 'created_at')
    op.drop_column('audiobooks', 'forked_from_id')
    op.drop_column('audiobooks', 'description')
    op.drop_table('work_queue')
    # ### end Alembic commands ###
