name: Nix CI Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  nix_build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v13

      - name: Start Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@v7

      - name: Build with Nix
        run: nix build
