name: Nix CI Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  nix_build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v13

      - name: Start Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@v7

      - name: Build with Nix
        run: nix build .#package

      - name: Check for frontend assets
        run: |
          echo "Checking for frontend assets in ./result..."
          ls -lh ./result/lib/python3.11/site-packages/glowtalk/static/dist/
          if [ ! -f ./result/lib/python3.11/site-packages/glowtalk/static/dist/bundle.js ]; then
            echo "Error: bundle.js not found!"
            exit 1
          fi
          # Assuming bundle.css might or might not be there, as per previous discussions.
          # If its presence is mandatory, uncomment the following check:
          # if [ ! -f ./result/lib/python3.11/site-packages/glowtalk/static/dist/bundle.css ]; then
          #   echo "Error: bundle.css not found!"
          #   exit 1
          # fi
          echo "Frontend assets check completed."

      - name: Run tests with Nix
        run: nix develop .#devShell --command pytest
