name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install uv
        uses: astral-sh/setup-uv@v1
        # Optionally, specify a uv version:
        # with:
        # version: "0.1.x" # Replace with a specific version if needed

      - name: Install dependencies
        run: uv pip install .[dev]
        env:
          UV_SYSTEM_PYTHON: '1'

      - name: Run tests
        run: pytest
